# Generated by Django 4.1.7 on 2023-03-29 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=25, unique=True)),
                ('category', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('size', models.CharField(max_length=25, unique=True)),
                ('price', models.FloatField(max_length=4, unique=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('url', models.URLField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('image_url', models.URLField(unique=True)),
                ('body', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
