# Generated by Django 4.1.7 on 2023-03-29 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_delete_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='T-Shirts', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(choices=[('Fight Gear', 'Fight Gear'), ('Street Wear Clothing', 'Street Wear Clothing'), ('Home Page', 'Home Page')], default='Fight Gear', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Scrap Poverty', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(choices=[(3.0, 3.0), (15.0, 15.0), (20.0, 20.0), (22.5, 22.5), (25.0, 25.0), (27.5, 27.5), (29.0, 29.0), (29.95, 29.95), (32.5, 32.5), (39.95, 39.95)], max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXL', 'Ttiple Extra Large')], default='S', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(choices=[('The Way', 'https://scrap-soldier-clothing-fight-gear.myshopify.com/products/the-way-addicted-to-the-mat-coach-bollinger'), ('Scrap Poverty', 'https://scrap-soldier-clothing-fight-gear.myshopify.com/products/scrap-poverty'), ('The Way', 'https://scrap-soldier-clothing-fight-gear.myshopify.com/products/the-way-addicted-to-the-mat-coach-bollinger'), ("The Original Fighter's Voice & Scrap Soldier Collaboration Long Sleeve Shirt", 'https://scrap-soldier-clothing-fight-gear.myshopify.com/products/the-original-fighters-voice-scrap-soldier-collaboration-long-sleeve-shirt'), ("The Original Fighter's Voice & Scrap Solider Collaboration Short Sleeve Shirt", 'https://scrap-soldier-clothing-fight-gear.myshopify.com/products/the-original-fighters-voice-and-scrap-solider-collaboration-shirt-short-sleeve'), ("The Original Fighter's Voice & Scrap Soldier Collaboration Pullover Hoodie", 'https://scrap-soldier-clothing-fight-gear.myshopify.com/products/the-original-fighters-voice-scrap-soldier-collaboration-pullover-hoodie'), ('North County MMA & Scrap Solider Collaboration Shirt', 'https://scrap-soldier-clothing-fight-gear.myshopify.com/products/north-county-mma-scrap-solider-collaboration-shirt'), ('Vale Tudo Shorts', 'https://scrap-soldier-clothing-fight-gear.myshopify.com/products/vale-tudo-shorts'), ('MMA Shorts (4 Way Stretch)', 'https://scrap-soldier-clothing-fight-gear.myshopify.com/products/mma-shorts'), ('Crop Hoodie For Woman', 'https://scrap-soldier-clothing-fight-gear.myshopify.com/products/crop-hoodie-for-woman'), ('Star Logo Sticker', 'https://scrap-soldier-clothing-fight-gear.myshopify.com/products/star-sticker'), ('Slant T-Shirt (Hottest Selling)', 'https://scrap-soldier-clothing-fight-gear.myshopify.com/products/slant-t-shirt'), ('Vertical Flag 1 Color', 'https://scrap-soldier-clothing-fight-gear.myshopify.com/products/destroy-your-demons'), ('Military Style Ribbon Hoodie', 'https://scrap-soldier-clothing-fight-gear.myshopify.com/products/military-style-ribbon-hoodie')], unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
