# Generated by Django 4.1.7 on 2023-03-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image_url_alter_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Hoodie', 'Hoodie'), ('Shorts', 'Shorts'), ('Stickers', 'Stickers'), ('Sporting Goods', 'Sporting Goods')], default='T-Shirts', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(choices=[('Fight Gear', 'Fight Gear'), ('Street Wear Clothing', 'Street Wear Clothing'), ('Home Page', 'Home Page')], default='Fight Gear', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(choices=[(3.0, 3.0), (15.0, 15.0), (20.0, 20.0), (22.5, 22.5), (25.0, 25.0), (27.5, 27.5), (29.0, 29.0), (29.95, 29.95), (32.5, 32.5), (39.95, 39.95)], max_length=5),
        ),
    ]
