# Generated by Django 4.1.7 on 2023-03-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_in_stock_product_instock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imageURL',
            new_name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inStock',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default=True),
        ),
    ]
